apiVersion: v1
kind: Service
metadata:
  name: tyfg9y7fyukf
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "tyfg9y7fyukf"
    port: 8080
  selector:
    app: tyfg9y7fyukf
